name: cwt_starter_template
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1

  ## -- STATE MANAGEMENT
  get: ^4.7.2
  get_storage: ^2.1.1

  ## -- OnBoarding PACKAGES
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.2.1

  ## -- OTP TEXT FIELD PACKAGE
  otp_text_field: ^1.1.3
  flutter_otp_text_field: ^1.1.1

  ## -- FIREBASE PACKAGES
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  flutter_facebook_auth: ^7.1.2
  google_sign_in: ^6.3.0


  ## -- ICON PACKAGES
  cupertino_icons: ^1.0.8
  line_awesome_flutter: ^3.0.1
  flutter_native_splash: ^2.4.6



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
    - assets/images/profile/
    - assets/images/dashboard/
    - assets/images/splash_images/
    - assets/images/welcome_images/
    - assets/images/forget_password/
    - assets/images/on_boarding_images/

# Splash screen has been added in the 'splash.yaml' file in main project directory